name: cafe_vitrin
description: Kafe ve e-ticaret uygulamaları için özelleştirilebilir, modern arayüz bileşenleri (widget'lar) sunan kütüphane.
version: 1.0.4
homepage: https://github.com/sebinc14/cafe_vitrin
repository: https://github.com/sebinc14/cafe_vitrin
issue_tracker: https://github.com/sebinc14/cafe_vitrin/issues

environment:
  sdk: ^3.13.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_animate: ^4.5.2
  carousel_slider: ^5.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
